# MySQL Database Information
mysql_host = 'localhost'
mysql_user = 'root'
mysql_pass = ''
mysql_db = 'weather-severity'

# Stopword List. These words will be removed from the free-text sections of CAP reports
# Based off of the default stopword list provided in Scikit-Learn
stopword_list = frozenset(
    ['all', 'less', 'being', 'indeed', 'over', 'anyway', 'not', 'own', 'through', 'yourselves', 'fify', 'where', 'mill',
     'only', 'find', 'before', 'whose', 'system', 'how', 'somewhere', 'with', 'show', 'had', 'enough', 'should', 'to',
     'whom', 'seeming', 'ours', 'has', 'might', 'thereafter',
     'latterly', 'do', 'them', 'his', 'around', 'than', 'get', 'very', 'de', 'none', 'cannot', 'every', 'whether',
     'they', 'front', 'during', 'thus', 'now', 'him', 'nor', 'name', 'several', 'hereafter', 'always', 'who', 'cry',
     'whither', 'this', 'someone', 'either', 'each', 'become', 'thereupon', 'sometime', 'side', 'therein',
     'because', 'often', 'our', 'eg', 'some', 'back', 'up', 'go', 'namely', 'towards', 'are',
     'further', 'beyond', 'ourselves', 'yet', 'out', 'even', 'will', 'what', 'still', 'for', 'bottom', 'mine', 'since',
     'please', 'per', 'its', 'everything', 'behind', 'un', 'above', 'between', 'it', 'neither', 'seemed',
     'ever', 'across', 'she', 'somehow', 'be', 'we', 'full', 'never', 'however', 'here', 'otherwise', 'were',
     'whereupon', 'nowhere', 'although', 'found', 'alone', 're', 'along', 'by', 'both', 'about', 'last',
     'would', 'anything', 'via', 'many', 'could', 'thence', 'put', 'against', 'keep', 'etc', 'amount', 'became', 'ltd',
     'hence', 'onto', 'or', 'con', 'among', 'already', 'co', 'afterwards', 'formerly', 'within', 'seems', 'into',
     'others', 'while', 'whatever', 'except', 'down', 'hers', 'everyone', 'done', 'least', 'another', 'whoever',
     'moreover', 'couldnt', 'throughout', 'anyhow', 'yourself', 'from', 'her', 'few', 'together', 'top',
     'there', 'due', 'been', 'next', 'anyone', 'much', 'call', 'therefore', 'interest', 'then', 'thru',
     'themselves', 'was', 'sincere', 'empty', 'more', 'himself', 'elsewhere', 'mostly', 'on', 'am',
     'becoming', 'hereby', 'amongst', 'else', 'part', 'everywhere', 'too', 'herself', 'former', 'those', 'he', 'me',
     'myself', 'made', 'these', 'bill', 'cant', 'us', 'until', 'besides', 'nevertheless', 'below', 'anywhere',
     'can', 'of', 'your', 'toward', 'my', 'something', 'and', 'whereafter', 'whenever', 'give', 'almost',
     'wherever', 'is', 'describe', 'beforehand', 'herein', 'an', 'as', 'itself', 'at', 'have', 'in', 'seem', 'whence',
     'ie', 'any', 'fill', 'again', 'hasnt', 'inc', 'thereby', 'thin', 'no', 'perhaps', 'latter', 'meanwhile', 'when',
     'detail', 'same', 'wherein', 'beside', 'also', 'that', 'other', 'take', 'which', 'becomes', 'you', 'if', 'nobody',
     'see', 'though', 'may', 'after', 'upon', 'most', 'hereupon', 'but', 'nothing', 'such', 'why',
     'a', 'off', 'whereby', 'i', 'whole', 'noone', 'sometimes', 'well', 'amoungst', 'yours', 'their', 'rather',
     'without', 'so', 'the', 'whereas', 'once'])

# storm_events_path - The path to the CSV generated by utils/FixAndCombineStormReports.py
storm_events_path = '/home/koppa/Documents/weather-severity-model/StormEvents/StormEventData.csv'

# cap_path - The full path to the directory housing your XML cap files. Assumes CAP reports end in "xml"
cap_path = '/home/koppa/Documents/weather-severity-model/noaa-cap-xml/'


def translateSeverity(direct_deaths, indirect_deaths, direct_injuries, indirect_injuries, property_damage, crop_damage):
    """
        TODO Implement and move this to a 'util' file
        Function to convert from predicted deaths/injuries/damage to severity
        Output: 1-4 (1 least severe, 5 most severe)    """
    return 1